/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-02-22T08:27:42.466Z[GMT]")
@Api(value = "github", description = "the github API")
public interface GithubApi {

    @ApiOperation(value = "", nickname = "githubCreateRepositoryGet", notes = "Auto generated using Swagger Inspector", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Auto generated using Swagger Inspector") })
    @RequestMapping(value = "/github/create_repository",
        method = RequestMethod.GET)
    ResponseEntity<String> githubCreateRepositoryGet(@ApiParam(value = "") @Valid @RequestParam(value = "body", required = false) String body);


    @ApiOperation(value = "", nickname = "githubGetRepositoryGet", notes = "Auto generated using Swagger Inspector", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Auto generated using Swagger Inspector") })
    @RequestMapping(value = "/github/get_repository",
        method = RequestMethod.GET)
    ResponseEntity<String> githubGetRepositoryGet();


    @ApiOperation(value = "", nickname = "githubUserDetailsGet", notes = "Auto generated using Swagger Inspector", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Auto generated using Swagger Inspector", response = String.class) })
    @RequestMapping(value = "/github/user_details",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> githubUserDetailsGet();

}
